refactor: lint and refactor pre-commit hook

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -3,9 +3,8 @@
 # Credit to Mr. DeVaughn-Brown
 
 # Check to see if we are on master branch. Stop accidental commits
-if [ $(git symbolic-ref HEAD 2>/dev/null) == "refs/heads/master" ]
-then
-  echo "Cannot commit to master branch"
-  exit 1
+if [ "$(git symbolic-ref HEAD 2>/dev/null)" == "refs/heads/master" ]; then
+	echo "Cannot commit to master branch"
+	exit 1
 fi
 exit 0
